
# sample sheet describing batch, sample and replicate
ATAC_SAMPLES: 'config/atac.tsv'
RNA_SAMPLES: 'config/rna.tsv'

# GRCh38 refseq
FA_HS38: '/gpfs/commons/groups/sanjana_lab/cdai/ref_genome/hs38/gencode_GRCh38.primary_assembly.genome.fa'

# BWA aln refseq
FA_HS38_BWA: '/gpfs/commons/groups/sanjana_lab/cdai/ref_genome/hs38/bwa_gencode_genome/gencode_GRCh38.primary_assembly.genome.fa' 

# STAR INDEX
STAR_INDEX: "/gpfs/commons/groups/sanjana_lab/cdai/ref_genome/hs38/star2.7.1a_gencode_genome"

# RSEM_INDEX
RSEM_INDEX: "/gpfs/commons/groups/sanjana_lab/cdai/ref_genome/hs38/rsem.1.2.21.gencode.v31.ref/hg38_gencode/hg38_gencode"

# Gencode GRCh38 gene name and gene id annotation
GENE_LOOKUP: '/gpfs/commons/groups/sanjana_lab/cdai/TFscreen/gencode_refseq_partial_modified_geneNames_ID_20191230.csv'

# Gencode GRCh38 gtf (converted to data.frame format)
GENCODE_HS38 : '/gpfs/commons/groups/sanjana_lab/cdai/ref_genome/hs38/gencode.v31.primary_assembly.annotation.pandas.df.20200108.txt'

# UCSC genome sizes, used by bedtools
HG38_GENOME_SIZES: '/gpfs/commons/groups/sanjana_lab/cdai/ref_genome/hs38/ucsc.hg38.chrom.sizes' 

# diffbind sample sheet
DIFFBIND_SAMPLES: 'config/diffBind_samplesheet.csv'


# Previously processed results
TF_LIST : '/gpfs/commons/groups/sanjana_lab/cdai/TFscreen/TFlist_20191230.csv'
HIT_LIST : '/gpfs/commons/groups/sanjana_lab/cdai/TFscreen/Hitlist_20191230.csv'

RNA_SAMPLE_NAMES: '/gpfs/commons/groups/sanjana_lab/cdai/TFscreen/RNASeqSampleNames.csv'
DESEQ_RESULT: '/gpfs/commons/groups/sanjana_lab/cdai/TFscreen/RNA-seq_timepoint_deseq_result_20200102.xlsx'
# log2fc was taken from Deseq2 output
RNA_HEATMAP_CLUSTERS_LOG2FC: '/gpfs/commons/groups/sanjana_lab/cdai/TFscreen/TF_RNAseq_Clusters_log2FC_20200708.xlsx'

# ATAC-seq consensus peaks (not merged, min2overlap) and read counts
ATAC_CONSENSUS_PEAKS: /gpfs/commons/groups/sanjana_lab/cdai/TFscreen/atac/diffbind/diffbind_consensu_min2overlap_NO_RECENTER.bed
ATAC_CONSENSUS_PEAKS_READS: /gpfs/commons/groups/sanjana_lab/cdai/TFscreen/atac/diffbind/diffbind_consensu_min2overlap_NO_RECENTER.txt




# MACS2 output columns
MACS2:
  NARROW:
    - chrom
    - start
    - end
    - peakname
    - score
    - strand
    - fc_peak # fold change at peak
    - negLog10p # -log10 pval at summit
    - neglog10q # -log10 qval at summit
    - summitpos # summit position relative to start

# previous processed bams sheet
PREVIOUS_BAMS: 'config/previous-bams-sheet.txt'

# annotation features bed files
GeneBody: 'resources/annotations/hs38/gencode_v31_protein_u2k_d1k.bed'
Intergenic: 'resources/annotations/hs38/gencode_v31_intergeneic_TSSup100kb-TSSup2kb.bed'
IntergenicAndGeneBody: 'resources/annotations/hs38/gencode_v31_protein_u100k_d1k.bed'

# intergenic region: upstream 100kb - upstream 3kb, no gene body
# first get all intergenic
# second get gene upstream 100kb - upstream 3kb
# intersect 1 & 2 to remove potential gene body overlaps from previous gene

JASPAR2020: '/gpfs/commons/groups/sanjana_lab/cdai/TFscreen/atac/JASPAR2020_combined_matrices_20191030.txt'

# crispr screen counts
CRISPR_COUNTS: 'resources/crispr/counts/RC.csv'
CRISPR_LOG2_RATIOS: '/gpfs/commons/groups/sanjana_lab/cdai/TFscreen/RCmNorRatioLog2.lu.csv'
